USE stocky_db;

-- =========================
-- INSERT 50 FINISHED PRODUCTS
-- =========================

INSERT INTO FinishedProducts (name, stock_quantity, unit_of_measure, comments) VALUES
('Lasagne bolognaise', 50, 'unit', 'Portion individuelle 350g'),
('Poulet rôti aux herbes', 30, 'unit', 'Poulet entier mariné'),
('Soupe aux légumes maison', 80, 'L', 'Soupe traditionnelle québécoise'),
('Chili con carne', 40, 'L', 'Recette épicée mexicaine'),
('Quiche lorraine', 25, 'unit', 'Quiche 8 portions'),
('Tourte au poulet', 35, 'unit', 'Tourte familiale'),
('Ratatouille provençale', 60, 'L', 'Légumes de saison'),
('Curry de légumes', 45, 'L', 'Version végétarienne'),
('Bœuf bourguignon', 30, 'L', 'Mijoté traditionnel'),
('Coq au vin', 25, 'L', 'Recette française classique'),
('Pad thaï', 40, 'unit', 'Portion individuelle'),
('Risotto aux champignons', 35, 'unit', 'Risotto crémeux'),
('Paella valenciana', 20, 'unit', 'Grande portion pour 4'),
('Shepherd''s pie', 45, 'unit', 'Pâté chinois version anglaise'),
('Moussaka', 30, 'unit', 'Plat grec traditionnel'),
('Sauce tomate maison', 100, 'L', 'Base pour pizzas et pâtes'),
('Pesto au basilic', 40, 'L', 'Pesto frais'),
('Sauce béchamel', 50, 'L', 'Sauce blanche classique'),
('Vinaigrette balsamique', 30, 'L', 'Pour salades'),
('Mayonnaise maison', 25, 'L', 'Sans conservateurs'),
('Guacamole frais', 20, 'kg', 'Fait quotidiennement'),
('Hummus', 35, 'kg', 'Recette libanaise'),
('Tzatziki', 25, 'kg', 'Sauce grecque au concombre'),
('Salsa mexicaine', 30, 'L', 'Piquante'),
('Sauce BBQ fumée', 40, 'L', 'Fumée au bois d''érable'),
('Pain de campagne', 100, 'unit', 'Pain rustique 500g'),
('Baguette traditionnelle', 150, 'unit', 'Baguette française'),
('Croissants au beurre', 200, 'unit', 'Croissants pur beurre'),
('Pain aux noix', 50, 'unit', 'Pain spécial aux noix'),
('Focaccia aux olives', 40, 'unit', 'Pain italien'),
('Brioche nature', 60, 'unit', 'Brioche moelleuse'),
('Pain complet', 80, 'unit', 'Pain santé aux grains entiers'),
('Muffins aux bleuets', 120, 'unit', 'Muffins frais'),
('Scones aux raisins', 90, 'unit', 'Style anglais'),
('Pain aux bananes', 45, 'unit', 'Gâteau-pain sucré'),
('Tarte aux pommes', 30, 'unit', 'Tarte 8 portions'),
('Gâteau au chocolat', 25, 'unit', 'Gâteau 12 portions'),
('Crème brûlée', 50, 'unit', 'Portion individuelle'),
('Tiramisu', 35, 'unit', 'Portion individuelle'),
('Cheesecake New York', 20, 'unit', 'Gâteau 12 portions'),
('Mousse au chocolat', 60, 'unit', 'Portion individuelle'),
('Panna cotta', 45, 'unit', 'Avec coulis de fruits'),
('Tarte au citron', 25, 'unit', 'Tarte meringuée'),
('Brownies', 100, 'unit', 'Carrés au chocolat'),
('Profiteroles', 40, 'unit', 'Lot de 4'),
('Jus d''orange frais', 80, 'L', 'Pressé du jour'),
('Smoothie fruits rouges', 50, 'L', 'Mélange de baies'),
('Limonade maison', 60, 'L', 'Citron et menthe'),
('Thé glacé pêche', 70, 'L', 'Infusion froide'),
('Café glacé', 40, 'L', 'Cold brew');
